# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# [0] Requirements
#  - datascience-lab base image

ARG CUDA_VER=11.3.1
ARG BASE_IMAGE=minimal_cuda

FROM samuel62/machine_learning_lab:${BASE_IMAGE}_${CUDA_VER}

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# Fix DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

RUN sudo apt-get update && \
    sudo apt-get install -y \
    freeglut3-dev && \
    rm -rf /var/lib/apt/lists/* && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER $NB_UID

RUN pip install --upgrade \
    jupyterlab-drawio \
    jupyter_contrib_nbextensions \
    jupyter_nbextensions_configurator \
    pyglet \
    rise \
    gym \
    garage \
    ipyleaflet && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN jupyter nbextension enable --py --sys-prefix ipyleaflet && \
    jupyter labextension install \
    jupyterlab-plotly \
    @jupyter-widgets/jupyterlab-manager \
    plotlywidget \
    @ijmbarr/jupyterlab_spellchecker && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER $NB_UID